name: dotnet test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        EULEX_WEBSERVICE_USERNAME: ${{ secrets.EULEX_WEBSERVICE_USERNAME }}
        EULEX_WEBSERVICE_PASSWORD: ${{ secrets.EULEX_WEBSERVICE_PASSWORD }}
      run: dotnet test --no-build --verbosity normal
