name: dotnet test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: Integration Testing

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        EULEX_WEBSERVICE_USERNAME: ${{ secrets.EULEX_WEBSERVICE_USERNAME }}
        EULEX_WEBSERVICE_PASSWORD: ${{ secrets.EULEX_WEBSERVICE_PASSWORD }}
      run: dotnet test --no-build --verbosity normal
